version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"

#  golang_service:
#    build: .
#    depends_on:
#      - elasticsearch
#    ports:
#      - "8080:8080"
#    volumes:
#      - .:/app
#    working_dir: /app
#    command: sh -c "go mod tidy && go run main.go"